spring:
  application:
    name: notification-service
  config:
    import: "configserver:http://config-server:${CONFIG_SERVER_PORT}"
  profiles:
    active: prod
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        max-attempts: 3