services:
  user-service:
    build:
      context: user-service
      args:
        PORT: ${USER_SERVICE_PORT}
    environment:
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://user-service:${USER_SERVICE_PORT}/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy

  notification-service:
    build:
      context: notification-service
      args:
        PORT: ${NOTIFICATION_SERVICE_PORT}
    environment:
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://notification-service:${NOTIFICATION_SERVICE_PORT}/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    
  eureka-server:
    build:
      context: eureka-server
      args:
        PORT: ${EUREKA_SERVER_PORT}
    environment:
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eureka-server:${EUREKA_SERVER_PORT}/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5

  config-server:
    build:
      context: config-server
      args:
        PORT: ${CONFIG_SERVER_PORT}
    environment:
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
      - CONFIG_URL=${CONFIG_URL}
      - CONFIG_ENCRYPTION_PASSWORD=${CONFIG_ENCRYPTION_PASSWORD}
      - CONFIG_ENCRYPTION_ALIAS=${CONFIG_ENCRYPTION_ALIAS}
      - CONFIG_ENCRYPTION_SECRET=${CONFIG_ENCRYPTION_SECRET}
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:${CONFIG_SERVER_PORT}/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5

  api-gateway:
    build:
      context: api-gateway
      args:
        PORT: ${API_GATEWAY_PORT}
    environment:
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - NOTIFICATION_SERVICE_PORT=${NOTIFICATION_SERVICE_PORT}
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      eureka-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy

  postgres:
    image: postgres:18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    attach: false

  kafka:
    image: apache/kafka-native:4.2.1
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,DOCKER://0.0.0.0:${KAFKA_BROKER_PORT}
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:${KAFKA_BROKER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    attach: false

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - "9090:9090"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      SERVER_PORT: 9090
    depends_on:
      - kafka
    attach: false