spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: http://user-service:8080
          predicates:
            - Path=/users/**
        - id: notification-route
          uri: http://notification-service:8081
          predicates:
            - Path=/notification/**

