spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PW}
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: kafka:${KAFKA_BROKER_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

