spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PW}
  jpa:
    hibernate:
      ddl-auto: create-drop
